mlfoundations/open_clip

README.md
I also changed s/source/conda/ in the command. It's the recommended way for Conda.
About removing `-f environment.yml`, note that's the default.
=> Add code highlighting to README and simplify env creation

src/training/train.py
The current codebase computes the validation accuracy on the GPU. If you have a validation set of ~20k examples, then this means you're multiplying a 20,000 x 20,000 matrix ~= 2GB of extra GPU memory. If you're maxing out the GPU memory for training the model, the extra 2GB can make a difference. This patch just moves it to the CPU. Things are a little bit slower, but it's not much in the grand scheme of things.
=> Perfom validation matrix multiply on CPU

src/training/main.py, src/training/params.py
The current code supports flags to save every N epochs (including every 1 epoch) but this fills up disk space quickly for big models. This new flag always writes the most recent epoch to `epoch_latest.pt` with whatever the last checkpoint is, allowing someone to see the current progress without creating a hundred checkpoint files.
=> New flag to save most recent epoch

src/training/distributed.py, src/training/main.py, src/training/model_configs/ViT-B-16.json, src/training/model_configs/ViT-L-14.json, src/training/params.py, src/training/zero_shot.py
Given that DataParallel is slower than DistributedDataParallel in single-node, multi-device use, and has issues working with torchscript and has other modelling complications, is likely to be deprecated in PyTorch at some point, I feel it's best to remove support and always use DDP or Horovod w/ appropriate launcher (torchrun, horovodrun, slurm, etc) for multi-gpu.
=> Remove DataParallel support. Minor cleanup.

.github/workflows/python-publish.yml
you need to create a token there https://pypi.org/manage/account/token/
and put it in there https://github.com/mlfoundations/open_clip/settings/secrets/actions/new
name it `PYPI_PASSWORD`
The release will be triggered when you name your commit `Release x.y.z`
I advise to change the version in setup.py in that commit
=> Add github action to automatically push to pypi on Release x.y.z commit

src/open_clip/model.py
Reusing the same ReLU module for multiple layers can make it more difficult for researchers as for example PyTorch's hook system won't work properly on the reused layer modules. I ran into this issue while building and testing interpretability tools on the CLIP models.
This PR doesn't change how any of the models work. It merely makes it possible to access and research each ReLU layer separately. Let me know if I need to make any changes before it can be merged!
I made a similar PR for OpenAI's CLIP repo that has already merged.
=> Don't reuse nn.ReLU modules

README.md, requirements-training.txt
There's a package necessary to build the latest code that's not included in the dependency file. This fixes that (and also adds a note to the README for how to fix set up the environment for running everything).
=> Add missing training packages and README note

README.md
Adapting SLURM section for current JUWELS Booster practices
- removing cpu-bind=none
- setting cpus-per-task=6 to fit better into current default task pinning scheme
=> Adjusting SLURM section

src/open_clip/factory.py, src/open_clip/loss.py, src/open_clip/model.py, src/open_clip/transform.py, src/open_clip/utils.py, src/training/data.py, src/training/main.py, src/training/params.py, src/training/train.py
WIP set of changes that reflect what's being used in current LAION training runs to support fine-tune, and possibly alternate epoch handling to handle case where maximum job runtime < full epoch of samples.
Done:
* support to resize (interpolate) the abs position embedding for default ViT impl, will allow fine tune at different resolutions
* support WDS 'ResampledShard', sample shards with replacement in each train process / dataloader worker instead of shuffling them across workers w/ a deterministic (epoch based) seed. This will allow resume in the middle of an epoch but may have an impact on training results
* improve epoch synchronization across worker processes, the ball was really dropped here for latest WDS impl 0.2.x and I don't see a way to make their scheme work across several …
=> PosEmbed resizing, Image pre-processing flexibility, WDS resampled shard option, worker epoch synch improvements

src/training/train.py
Creates an `AverageMeter` keeping track of the sample throughputs across the entire job and reports the average. This fixes #128.
=> Show Samples / Sec during logging

src/training/main.py, src/training/params.py, src/training/precision.py, src/training/train.py, src/training/zero_shot.py
At large model/data/batch size, float16 amp is not stable with clip training.
amp bfloat16 solves this problem while being 20% faster.
tf32 is only 8% slower than amp float16 and even more stable.
=> Implement bfloat16 option and enable tf32 by default.

src/training/main.py
seems this is strictly better:
worst case it's just as bad as random wandb name
best case you need to change nothing/less
=> wandb: initialize name to args.name

src/training/train.py
`src/open_clip/params.py` currently contains a definition for a `--skip-scheduler` flag that is not used anywhere in the codebase. This is a one-line patch to fix this and make `--skip-scheduler` actually disable the learning rate scheduler in training.
=> Honor the --skip-scheduler flag

src/open_clip/pretrained.py, tests/test_download_pretrained.py
Fixes #143 
```
$ PYTHONPATH=src python -m pytest tests
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/fabio/workspaces/oss/open_clip
plugins: forked-1.4.0, xdist-2.5.0
collected 7 items                                                                                                                                                                            
tests/test_download_pretrained.py ......                                                                                                                                               [ 85%]
tests/test_simple.py . …
```
=> Add checksum verification for pretrained model weights downloaded from mlfoundations github org

README.md, src/open_clip/pretrained.py, tests/test_inference_simple.py
A ViT-B/32 with roberta base encoder with a 61.7% top-1 ImageNet-1k zero-shot was trained on stability. See model details here https://huggingface.co/laion/CLIP-ViT-B-32-roberta-base-laion2B-s12B-b32k This is the first openclip model using a HF text tower. It has better performance on a range of tasks compared to the standard text encoder, see [metrics](https://huggingface.co/laion/CLIP-ViT-B-32-roberta-base-laion2B-s12B-b32k/blob/main/unknown.png)
=> Add roberta base ViT-B/32 pretrained.

.github/workflows/ci.yml, .github/workflows/clear-cache.yml, Makefile, README.md, requirements-test.txt, tests/test_training_simple.py, tests/util_test.py
This PR utilizes pytest-split to split the test set based on test durations.
It also uses a cache to reuse the virtual env between runs unless `requirements*.txt` have changed. This allows skipping the setup step except on the first run, which will build the cache.
I've enabled testing for macos just to ensure that everything still works as expected with a different runner.
For this I had to add a `skipif` condition to the training test, as it was failing when pickling on MacOs.
Overall this should reduce testing times to 2-4 minutes and scale better with more tests in the future.
=> Parallelize CI tests

README.md, src/open_clip/pretrained.py
A ViT-H/14 with xlm roberta large encoder with a 77.0% (vs 78% for the english equivalent) top-1 ImageNet-1k zero-shot was trained on stability. See model details here https://huggingface.co/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k
This model was trained following the [LiT](https://arxiv.org/abs/2111.07991) methodology: the image tower was frozen (initialized from english openclip ViT-H/14), the text tower was initialized from [xlm roberta large](https://huggingface.co/xlm-roberta-large) and unfrozen. This reduced training cost by a 3x factor.
See full english [metrics](https://huggingface.co/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k/resolve/main/results_xlm_roberta_large.png)
On zero shot classification on imagenet with translated prompts this …
=> Add pretrained ('xlm-roberta-large-ViT-H-14', 'frozen_laion5b_s13b_b90k')

src/training/data.py, src/training/params.py
The current code ignores samples where the image ends with `jpeg`, when there is no need to. In the extreme case where all the samples have the `jpeg` extension, the current code will silently hang forever with the `--dataset-resampled` flag, as it will keep trying to find valid samples but there will be none.
=> fixing data filtering

requirements.txt
For compatibility with googleapis packages when installing with conda
=> Less stringent protobuf requirement

.github/workflows/ci.yml
Changes CI to run regression tests against latest release (v2.8.2 at time of writing)
=> Regression test against v2.8.2

src/open_clip/loss.py
Currently captioning loss is ignoring the wrong pad tokens, open_clip tokenizer uses 0 and not -100.
=> Ignore pad tokens in captioning loss

src/open_clip/coca_model.py, src/open_clip/generation_utils.py, src/open_clip/transformer.py
This PR should add the `generate` method to the CoCa model to add support for generation
based on https://github.com/lucidrains/x-transformers/blob/main/x_transformers/autoregressive_wrapper.py
=> add `generate` to coca model

src/training/data.py
These small changes allow training on a webdataset that contains webp images.
For example, the [img2dataset tool](https://github.com/rom1504/img2dataset) has webp as an image encoding option.
=> Allow webp in webdataset

src/training/train.py
Multiply the batch size by the `accum-freq` argument to get the effective batch size and so compute the real number of samples.
=> Correct num_samples logging

src/training/data.py, tests/test_num_shards.py
Currently handling complex webdataset url patterns in `args.train_data` can lead to a unnecessary memory explosion, when using `::` to concatenate multiple data sources. This can be correctly parsed by webdataset, using `wds.shardlists.expand_urls(urls))`.
See Issue https://github.com/mlfoundations/open_clip/issues/278.
=> Fix braceexpand memory explosion for complex urls

src/open_clip/coca_model.py, src/open_clip/hf_model.py, src/open_clip/loss.py, src/open_clip/model.py, src/open_clip/model_configs/coca_ViT-B-32.json, src/open_clip/model_configs/coca_base.json, src/open_clip/model_configs/coca_roberta-ViT-B-32.json, src/open_clip/transformer.py, src/training/train.py, tests/test_inference.py
This PR adds the possibility to use a CLS token as a model parameter in TextEncoder to simplify the logic of `CoCa`
=> use `TextEncoder` in coca `encode_image`

src/training/main.py
Set `id` to `args.name` when initializing wandb so multiple parallel runs are not collapsed into a single one. See https://github.com/mlfoundations/open_clip/issues/340.
=> set wandb id to args.name

src/training/train.py
bug pointed out by @GeorgiosSmyrnis -- it was
```
if i_accum % args.log_every_n_steps:
.. do logging ..
```
but should be
```
if i_accum % args.log_every_n_steps == 0:
.. do logging ..
```
=> bug fix in logging every n steps

README.md, requirements-training.txt, src/training/file_utils.py, src/training/main.py, src/training/params.py
This PR introduces two additional arguments, which are `--sync-s3` and `--sync-s3-frequency`. Recommended use is to do `--sync-s3 s3://<path-to-bucket>` and `--logs /scratch/logs` which is hopefully local ssd.
Then, as you run, you should see logs at `/scratch/logs/<name>` and `s3://<path-to-bucket>/<name>`. So you don't have to use the local file system.
This PR also supports loading from `s3://<path-to-checkpoint>` -- it's a bit slow but not too bad.
=> Utility for sycning with s3 and loading checkpoints from s3

tests/test_inference.py
@lopho @rwightman @rom1504 
This models with names starting with "timm" don't exist anymore but the equivalent ones appear to still be unavailable in timm so I rename them in the tests too
=> rename timm models in tests

src/open_clip/factory.py, src/training/main.py, tests/test_download_pretrained.py
Adds the option to load any model hosted on the hub using the `hf-hub:` prefix.
For this to work, the model repositories would need an `open_clip_config.json` file uploaded with the configuration values currently hosted in json file in this repository.
Here's an example of a working repository: https://huggingface.co/lysandre/CLIP-ViT-L-14-laion2B-s32B-b82K
Here's how this would be used in practice:
```py
import open_clip
model, _, preprocess = open_clip.create_model_and_transforms('hf-hub:lysandre/CLIP-ViT-L-14-laion2B-s32B-b82K')
tokenizer = open_clip.get_tokenizer('hf-hub:lysandre/CLIP-ViT-L-14-laion2B-s32B-b82K')
```
fix https://github.com/mlfoundations/open_clip/issues/290
=> Fetch from Hugging Face Hub using hf_hub: prefix

src/open_clip/hf_model.py, src/open_clip/model.py, src/open_clip/transformer.py, tests/test_inference.py, tests/util_test.py
@rwightman @iejMac @rom1504 
@rwightman was saying that booleans should be ok for torchscript, if I understand they are but to avoid checking all branches output the same thing one needs to make them constants https://pytorch.org/docs/stable/jit_language_reference.html#python-defined-constants 
In this PR I annotate them as constants and it seems to work. Let me know if this is ok and thank you for all the reviews
=> better torchscript and small test refactor

src/training/file_utils.py
Jenia pointed out that s3 log message unnecessary prints on relative paths
=> Unescessary log on relative path

README.md, src/training/data.py, src/training/params.py
When using multiple data sources (e.g. `--train-data=path/to/dir/1/{000..999}.tar::path/to/dir/2/{000..999}.tar`), allow the different sources to be sampled with different weights (e.g. by using `train-data-weights=100::1`)
=> [WIP] Add support for dataset mixtures with different sampling weights

src/training/train.py, tests/test_training_simple.py
Should fix #418  
Hi @iejMac @rom1504 @usuyama, It should be the other way around, `output_dict` should be removed because it is passed to `create_model_and_transforms` in main.py, however there was also another small issue while accumulating grads, that should be fixed here.
I tried it and it seems to work ok, however, @iejMac could you maybe try it too and see if training goes as it should?
=> fix accum-grad training

src/open_clip/hf_configs.py, src/open_clip/hf_model.py
TODO need to figure out best way of handling the change in default `user_pooler_output` from True to False for the PubMed config https://github.com/usuyama/open_clip/blob/01a53cc46662d8b28da0c9d73271bfb8f6f4b20d/src/open_clip/hf_model.py#L69
NOTE this is to support https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224
=> Add HF BERT configs for Microsoft PubMed CLIP model

README.md, src/open_clip/utils.py, src/training/main.py, src/training/params.py
This PR introduces beta support for int8 training and inference. You can enable int8 training with `--use-bnb-linear SwitchBackLinearGlobal` or `--use-bnb-linear SwitchBackLinearGlobalMemEfficient`. For CLIP VIT-Huge this should currently correspond to a 10% training speedup with negligable accuracy difference. 
More speedups coming when the attention layer is refactored so that linear layers may be replaced there, too. However, that will require more changes so best to get this merged first.
=> int8 support

src/training/data.py
For debugging purposes, sometimes is convenient to use a serial data worker (the number of workers is 0 for the `DataLoader`). For this to work fine, `persistent_workers` needs to be disabled, which is what I change here (conditional to the number of workers value).
=> Support serial-worker training

src/open_clip/loss.py
The `CoCaLoss` class currently performs a forward pass to calculate the `clip_loss` regardless of the value of `self.clip_loss_weight`. During CoCa finetuning, `self.clip_loss_weight` is set to 0, yet the forward pass is still executed. I have added a simple "if" statement and default `clip_loss` value to skip the forward pass when `self.clip_loss_weight` is set to 0.
=> default clip_loss to 0 when self.clip_loss_weight is 0

src/open_clip/loss.py
to avoid computing clip loss when it is zero we still need a tensor otherwise it errors somewhere else.
=> default clip loss

src/training/params.py
Default workers of 1 results in incredibly slow dataloading if someone didn't remember to change the setting. 4 is a more reasonable value without being too large as to cause concerns with smaller datasets or oversubscribed CPUs.
=> Update default # workers from 1 -> 4

src/training/main.py
Pytorch 2.0 adds `_orig_mod.` prefix to keys of state_dict() of compiled models. For compatibility, we save state_dict() of the original model, which shares the weights without the prefix.
I have verified this workaround by resuming model training from a checkpoint created after a few epochs of compiled model training. The behaviors are within the expected randomness from the original trajectory. See also PyTorch forum topic "[How to save/load a model with torch.compile](https://discuss.pytorch.org/t/how-to-save-load-a-model-with-torch-compile/179739)".
=> compiled model state_dict() workaround

src/open_clip/factory.py, src/open_clip/loss.py, src/open_clip/model.py, src/training/main.py, src/training/params.py, src/training/train.py
=> SigLIP impl

src/open_clip/coca_model.py
CoCa `generate()` fails on `transformers>=4.31.0` due to [fixes](https://github.com/huggingface/transformers/commit/43479ef98f2d9f1600793922cf022d7d0670a5f8)  in `BeamSearchScorer`. 
Specifically, the following snippet:
```
model, _, transform = open_clip.create_model_and_transforms(
model_name="coca_ViT-L-14",
pretrained="mscoco_finetuned_laion2B-s13B-b90k"
)
PIL_image = Image.open(im_path).convert("RGB")
im = transform(PIL_image).unsqueeze(0)
with torch.no_grad(), torch.cuda.amp.autocast():
generated = model.generate(im)
```
results in:
```
in _generate_beamsearch(self, image_inputs, pad_token_id, eos_token_id, sot_token_id, num_beams, num_beam_groups, min_seq_len, stopping_criteria, logit_processor, logit_warper)
329 
330         if num_beams * batch_size != batch_beam_size:
--> 331 …
```
=> Integrate Updates to BeamSearchScorer

src/training/data.py
Currently the code will fail if you try to have multiple datasets with a resample factor because it will assert trying to resample erroneously even during test time. This PR makes sure we only have the assert statement during train time rather than test time. See this [issue](https://github.com/mlfoundations/open_clip/issues/632)
=> Only assert reshuffle if we are in train mode and we specify a data upsample refactor

README.md, src/training/train.py
Currently we are passing `step` to wandb as another metric instead of using the `step` argument to `wandb.log` (see https://docs.wandb.ai/ref/python/log). This causes two "step" variables to be logged and can cause inconsistencies.
=> Log wandb step using wandb native step arg in addition to the "step" key.

src/open_clip/factory.py
=> Checking model_cfg instead of model_name to load CoCa model.

requirements.txt
Remove the version limit for protobuf since it's no longer needed. The version limit was added because of this issue #246 but that has been resolved in the transformers library with [this](https://github.com/huggingface/transformers/pull/24599) pull request and [commit](https://github.com/huggingface/transformers/commit/299aafe55ff03c565c059682c6fd312e4b89bc2f).
Fixes #623
=> remove version limit for protobuf

src/open_clip/transform.py
This PR fixes 2 things in `transform.PreprocessCfg`:
* An assert on `mode` was incorrectly checked. Note that `(var)` isn't the same as `(var,)`. The former is the same as `var`, with redundant parentheses. The assert was working because the following is true `"RGB in "RGB"`.
* `PreprocessCfg.num_channels` is not a function but a property, so it doesn't carry parentheses.
=> Fix undesired behavior of `transform.PreprocessCfg`

src/open_clip/model.py
For this PR, I'm not 100% sure it's a bug but it feels like it is. This function first checks there's an "image_mean" attribute but then gets a different one ("mean"). Similarly for "std". So it fixes this.
=> Fix `model.get_model_preprocess_cfg`

src/open_clip/zero_shot_classifier.py
This is a minor change but makes things more consistent, as the training code also normalizes embeddings by using the flag in `encode_text`:
https://github.com/mlfoundations/open_clip/blob/a6bb37c7e24222e1aafd75e752b1877fa9c3278f/src/open_clip/model.py#L294
=> Make Text Embedding Normalization During Zero Shot Inference Consistent With Training

src/open_clip/coca_model.py
I recently saw the following change that adds `logit_bias` to `CoCa`: https://github.com/mlfoundations/open_clip/commit/6f05e1dfe9d19782978466f4a815c44bcf40ad6a
However, I think it misses using this parameter if it's non-null. This PR changes this, to use it as in `CLIP` or `CustomTextCLIP`.
=> Fix missing return of "logit_bias" in `CoCa.forward`

src/open_clip/factory.py, src/open_clip/model.py, src/open_clip/tokenizer.py
Hi!
I want to make OpenCLIP more usable for downstream applications, like zero-shot classification. Right now, to get the logits, the user has to call `encode_image` and `encode_text`, then matmul them, multiply the result by `logit_scale`, and optionally add `logit_bias`. I think it makes sense to have one method to get logits, as in OpenAI and HuggingFace. So I added the `get_logits` method to both `CLIP` and `CustomTextCLIP` classes.
I also added the `NLLBTokenizer` class that has an additional `langs` parameter in the `__call__` method. This is needed because the tokenizer for NLLB models adds a language token to the beginning of the sequence. The token that is added is controlled via the `set_src_lang_special_tokens` method. If the language is not set via this method, the tokenizer …
=> Add `get_logits` method and NLLB tokenizer

docs/clipa.md
The CLIPA tokenizer description as it exists right now isn't exactly correct. In order to use any of the masking you need to add 
```
"tokenizer_kwargs": {
"reduction_mask": "syntax"
}
```
as a configuration within `text_cfg`.  This PR fixes the documentation.
=> Fix clipa tokenizer documentation

src/open_clip/tokenizer.py
`**kwargs` parameter is missing from `HFTokenizer`.
For example I'm unable to pass a cache_dir parameter in order to define a certain working directory.
=> Add **kwargs to HFTokenizer

src/open_clip/tokenizer.py
Avoid calling `str.maketrans` repeatedly, and de-duplication white spaces with join+split ([split act on the same whitespaces](https://docs.python.org/3/library/stdtypes.html#str.split))
About ~~x1.5~~ x3 speedup, on a tiny and already fast function but this is called very often
=> Re-use str.maketrans

src/open_clip/coca_model.py
**fix #847**
The stopping criteria is updated in the latest `transformers`(V4.39.3 now). The return result is modified to a tensor (`torch.full((input_ids.shape[0],), is_done, device=input_ids.device, dtype=torch.bool)` ) instead of a bool value, which causes the bug in #847
**the related code in `transformers`**
https://github.com/huggingface/transformers/blob/0bd58f1ce0573c0e3269de4215a17d318add49b9/src/transformers/generation/stopping_criteria.py#L76
=> Fix stopping_criteria result check in coca_model

src/open_clip/factory.py, src/open_clip/model_configs/RN50x16-quickgelu.json, src/open_clip/model_configs/RN50x4-quickgelu.json, src/open_clip/model_configs/RN50x64-quickgelu.json, src/open_clip/model_configs/ViT-H-14-378.json, src/open_clip/model_configs/ViT-L-14-336-quickgelu.json, src/open_clip/pretrained.py, src/open_clip/push_to_hf_hub.py, src/open_clip/tokenizer.py, src/open_clip_train/main.py, src/open_clip_train/params.py
* all weights not already on the hub uploaded to timm org for simplicity & safety (metaclip models were incompatible with weights_only=True).
* OpenAI models no longer use special path that loads from torchscript archive, use same path as other models
* Handling of QuickGELU consistent btw openai and non, made a bit more safe, warn on mismatch
* safetensors is default weight load if available
=> All default pretrained weights pushed to HF hub

src/open_clip/model_configs/ViTamin-L-384.json, src/open_clip/model_configs/ViTamin-L2-384.json
In `src/open_clip/model_configs`, two configs of the ViTamin series are missing: `ViTamin-L-384` and `ViTamin-L2-384`.
The two added models are evaluated (with pretrained weights) on the Datacomp benchmark, where `ViTamin-L-384` has 81.83% ImageNet top 1 and 67.12% Average, and `ViTamin-L2-384` has 82.05% ImageNet top 1 and 67.97% Average, matching the performance reported in the paper.
=> add missing ViTamin configs

src/open_clip/factory.py, src/open_clip/loss.py, src/open_clip_train/params.py
=> Experimenting with alternative siglip loss impl for better dist scaling

src/open_clip/coca_model.py, src/open_clip/model.py, src/open_clip/modified_resnet.py, src/open_clip/timm_model.py, src/open_clip/transformer.py, src/open_clip/utils.py
Compatible with timm approach (passes through to timm image encoders) and adding to builtin image and text...
This is a different approach than #731, but as with timm, I found the idea of integrating the output_hidden_states approach to be like HF Transformers to be a bit of a headache and risk too many regressions. This approach duplicates some code, but it makes typing less problematic, and keeps the main forward functions lean for training, normal use.
=> API for getting intermediate image and text features, forward_intermediates()

src/open_clip/pretrained.py
This PR removes the MetaCLIP 2 L/14 model checkpoint entry that does not exist anymore.
- This model was invalid / not hosted anymore: https://huggingface.co/timm/vit_large_patch14_clip_224.metaclip2_worldwide
- Keeping the entry may cause confusion for users trying to load the model
- Other MetaCLIP 2 checkpoints are untouched
This change ensures that only available and verified checkpoints remain in the model registry.
=> Remove non-existent MetaCLIP 2 L/14 checkpoint
