src/open_clip/factory.py, src/open_clip/model.py, src/open_clip/model_configs/timm-resnetblur50.json, src/open_clip/timm_model.py, src/open_clip/utils.py, src/training/main.py, src/training/params.py
=> Locked image tower support

src/training/data.py, src/training/main.py
Two wds dataset handling changes to be tested on JUWELS before merge, rare exception throw on certain LAION shuffle orders.
Restart uses same shuffle seed as train start without passing epoch through.
=> nothrow in tarfile to samples, pass epoch arg through to detshuffle

README.md
=> Include the "Data Determines Distributional Robustness in CLIP" paper

src/open_clip/tokenizer.py
A fix for https://github.com/mlfoundations/open_clip/issues/130
=> Change the last token to eot_token truncating

src/training/main.py
Decrease vram usage. Neccessary for g/14
thanks @Nodja
=> Load checkpoint on cpu, then loads into already on gpu model

src/training/data.py, src/training/main.py, src/training/params.py
This adds a new dataset type (`--dataset-type synthetic`) that can be used for benchmarking purposes.
=> support synthetic data for benchmarking purposes

src/open_clip/__init__.py, src/open_clip/factory.py
=> Possible interface for create fn with mandatory pretrained arg and inference only transform

README.md
lock-text-unlocked-layers goes with lock-test
=> Add --lock-text in HF example.

src/open_clip/model_configs/timm-convnext_base_w.json, src/open_clip/model_configs/timm-convnext_small.json, src/open_clip/model_configs/timm-convnext_tiny.json
Roughly matching size of smallest 3 resnet configs
=> Add (tiny, small, base_w) convnext configs 

src/training/data.py
Add more comments, fix a tab/space issue someone added
=> Improve spacing of epoch seed increments across local workers

src/open_clip/transformer.py
=> wrapped patchdropout in a torch.nn.Module

src/open_clip/transformer.py
Previously layer scale 0 would result in identity
=> Ability to set layer scale to 0

src/open_clip/coca_model.py, src/open_clip/transformer.py
This is supposed to make the `encode_image` of CoCa simpler without breaking things with respect to the currently trained model 
https://huggingface.co/laion/CoCa-ViT-B-32-laion2B-s13B-b90k/blob/main/epoch_95.pt 
it might not be the best way but I thought I would open the PR anyway to see which way it should be done.
=> simplify encode_image

src/open_clip/coca_model.py
this is supposed to add a mask to the attention preventing the CLS token at the end of the sequence from attendin to padded tokens.
=> Add cls mask

src/training/distributed.py, src/training/main.py
Re #301 
I haven't tested this yet, but will next time I get pre-empted
=> PoC for a resume that searches for last checkpoint if `--resume latest` arg set

.github/workflows/ci.yml, src/open_clip/coca_model.py, src/open_clip/hf_model.py, src/open_clip/model.py, src/open_clip/model_configs/coca_ViT-B-32.json, src/open_clip/model_configs/coca_base.json, src/open_clip/model_configs/coca_roberta-ViT-B-32.json, src/open_clip/transformer.py, src/training/train.py, tests/test_inference.py, tests/util_test.py
This should make clip and coca compatible with jit although for coca this needs to be fixed first https://github.com/pytorch/pytorch/issues/92073
=> Add tests bis

docs/script_examples/stability_example.sh
Using remote sync and resume latest.
=> Example slurm script

src/open_clip/model.py
@rom1504 I left an unused argument
=> remove output_dict argument

src/open_clip/coca_model.py, src/open_clip/transformer.py, tests/util_test.py
refactor coca according to @rwightman suggestion and remove extra layer_norm
=> Refactor model

src/open_clip/model_configs/coca_ViT-L-14.json
Training report : https://wandb.ai/iejmac/open-clip/reports/CoCa-L-14--VmlldzozNDEwMDIx
=> Add CoCa-ViT-L/14 config

src/open_clip/coca_model.py
This should add support in generate for min_seq_len and stop ignoring eos_token_id in `generate`
=> Add min_seq_len and support for eos_token_id in  `generate`

README.md
Adds a way to perform fine-tuning in the README @rom1504
=> CoCa fine tune instruction in readme

src/open_clip/model.py, src/open_clip/transformer.py
https://arxiv.org/abs/2302.01327v1
They have a section in there where they apply this to LiT
Seems like a free lunch, experiments are convincing :+1:
=> add dual patchnorm as an option

README.md, src/open_clip/__init__.py, src/open_clip/factory.py, src/open_clip/loss.py, src/training/main.py, src/training/params.py, src/training/train.py
Still need to test, made changes again but after CoCa merge
=> Distillation

src/open_clip/coca_model.py
@rwightman @rom1504 I made transformers non-optional in the last PR, sorry. Should fix #420
=> make transformers optional

README.md
Pretty sure that this is the intention given the context
=> Fix typo: "close openclip" -> "clone openclip"

README.md
=> Fix malformed `--train-data` argument example

src/open_clip/model_configs/ViT-B-32-256.json, src/open_clip/pretrained.py
Add model from https://huggingface.co/laion/CLIP-ViT-B-32-256x256-DataComp-s34B-b86K.
```python
model,  _, transform = open_clip.create_model_and_transforms('ViT-B-32-256', pretrained='datacomp_s34b_b86k')
```
=> Add CLIP-ViT-B-32-256x256-DataComp-s34B-b86K

src/open_clip/factory.py
Allows SigLIP models to be trained with SigLIP loss via --siglip (avoid dupe arg)
=> Merge model_cfg & model_kwargs before passing to model

src/open_clip/coca_model.py
@gpucce wouldn't this be a cleaner approach to #691? the context_len (length of input text tokens) IS 76 so it doesn't make sense to feed it 77 and then always remove one token...
=> Remove cls_embed arg from forward/encode_image fns

src/training/params.py
"BatchNorm" -> "LayerNorm" in the description string for "--lock-text-freeze-layer-norm"
=> Update params.py: "BatchNorm" -> "LayerNorm" in description string

requirements-test.txt, requirements-training.txt, requirements.txt, setup.py
they are optional deps for rarely used model configs
=> Remove explicit sentencepiece / protobuf deps 

src/open_clip/coca_model.py, src/open_clip/transformer.py, src/training/train.py, src/training/zero_shot.py
still need to look at mask changes for text fastpath
=> Default Transformer MHA to batch_first, enables fastpath for vit

.github/workflows/ci.yml, src/open_clip/convert.py, src/open_clip/factory.py, src/open_clip/model_configs/ViT-B-16-SigLIP2-256.json, src/open_clip/model_configs/ViT-B-16-SigLIP2-384.json, src/open_clip/model_configs/ViT-B-16-SigLIP2-512.json, src/open_clip/model_configs/ViT-B-16-SigLIP2.json, src/open_clip/model_configs/ViT-B-32-SigLIP2-256.json, src/open_clip/model_configs/ViT-L-16-SigLIP2-256.json, src/open_clip/model_configs/ViT-L-16-SigLIP2-384.json, src/open_clip/model_configs/ViT-L-16-SigLIP2-512.json, src/open_clip/model_configs/ViT-SO400M-14-SigLIP2-378.json, src/open_clip/model_configs/ViT-SO400M-14-SigLIP2.json, src/open_clip/model_configs/ViT-SO400M-16-SigLIP2-256.json, src/open_clip/model_configs/ViT-SO400M-16-SigLIP2-384.json, src/open_clip/model_configs/ViT-SO400M-16-SigLIP2-512.json, src/open_clip/model_configs/ViT-gopt-16-SigLIP2-256.json, src/open_clip/model_configs/ViT-gopt-16-SigLIP2-384.json, src/open_clip/pretrained.py, src/open_clip/push_to_hf_hub.py, src/open_clip/tokenizer.py
Preparing for SigLIP 2 weights
=> Add SigLIP2 models

README.md
Updated README sample code to address #1049
=> Updated PyTorch code in README 

src/open_clip/factory.py
Also
* add support to load specific image / text tower weights
* refine consistency for image (timm), text (hf) pretrained weight loading on init Currently lots of logs while testing
=> Initial work on adding local-dir: schema for model & tokenizer loading from local folder

src/open_clip/factory.py, src/open_clip/loss.py, src/open_clip_train/main.py, src/open_clip_train/params.py
Also,
* pass through model factory fns 
* add docstrings to create_model_and_transforms and create_model_from_pretrained fns
* pss through new pretrained tower args
=> Add --force-context-length argument

src/open_clip/transformer.py
Offers a correct option for CoCa cls mask, and an optional padding mask for non-causal use
=> An alternative text masking helper fn
